### PR TITLE
Updated README.md with project repo name for following recommended practices

### LINKED ISSUE #1: link not working on README.md page
link not working on README.md page

error:

image

update [ README.md documentation here](https://github.com/RakibHassan01/imdb_nextJS/blob/main/README.md)

### LINKED ISSUE #4: Updated README.md with project name for following recommended practices
i saw this project readme.md doc, there is no project repo name specified;
Updated README.md with project repo name for following recommended practices

### PR DESCRIPTION
**Pull request by farhan7reza7**
Update README.md with project name for following recommended practices

resolves #4

### CODE REVIEW

**Review by farhan7reza7 — COMMENTED** [review]
everything is okay now, link is working now

**Comment by justrakibhassan** [comment]
Update live site URL :)

**Review by farhan7reza7 — COMMENTED** [review]
all okay

**Review by farhan7reza7 — COMMENTED** [review]
Updated README.md with project name for following recommended practices

**Review by justrakibhassan — APPROVED** [review]
review site live URL

**Comment by RakibHassan01** [comment]
update link-updater

**Pull request merged**
